# Generated by Django 5.0 on 2024-01-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='apellidoMaterno',
            new_name='apellido',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='apellidoPaterno',
        ),
    ]
