# Generated by Django 5.0 on 2024-01-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academica', '0003_remove_estudiante_vigencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='carrera',
            field=models.CharField(max_length=50),
        ),
    ]
