# Generated by Django 5.0 on 2024-01-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academica', '0006_rename_id_matricula_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('roles', models.CharField(choices=[('usuario', 'Usuario'), ('admin', 'Administrador')], default='usuario', max_length=7)),
            ],
        ),
    ]
