# Generated by Django 5.0 on 2024-01-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academica', '0007_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='username',
            new_name='nombre_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='roles',
        ),
    ]
