# Generated by Django 5.0.1 on 2024-01-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academica', '0008_rename_username_usuario_nombre_usuario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
